homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret castillo_lat
  longitude: !secret castillo_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret castillo_elev
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  customize: !include customize.yaml

###############################################################
######  Configuration
###############################################################
config:

frontend:

http:
  api_password: !secret ha_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret url_name
  ip_ban_enabled: True
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
    - fd00::/8
    
updater:
  include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

logbook:
# View all events in a logbook

#view log of services
logger:

# Enables a map showing the location of tracked devices
map:

###############################################################
######  Components
###############################################################

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

media_player:
  - platform: directv
    host: !secret directv_host
    port: 8080
    name: Downstairs DirecTV
    device: 0

  - platform: directv
    host: 192.168.1.44
    port: 8080
    name: Upstairs DirecTV
    device: !secret directv_device

# Cloud
cloud:

#Alexa
alexa:

#Rachio iframe panel_iframe
panel_iframe:
  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump

#Nest Integration
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
    
#Apple TV 
apple_tv:
  - host: !secret castillo_appletv_ip
    login_id: !secret castillo_appletv_login
    name: Apple TV 4K
   
zwave:
  usb_path: /dev/ttyACM0
  
# IFTT Craig
ifttt:
  key: !secret iftt_key

# Device Trackers
device_tracker:
  - platform: icloud
    username: !secret ck_apple_id
    password: !secret ck_apple_pw
    account_name: !secret ck_apple_nm
  - platform: icloud
    username: !secret ar_apple_id
    password: !secret ar_apple_pw
    account_name: !secret ar_apple_nm 
 
###############################################################
######  Panels & Interface
###############################################################
 
#History Graph 
history_graph:
  gr1:
    name: Castillo Temperature
    entities:
      -  climate.dining_room
      -  sensor.dining_room_thermostat_hvac_state
      -  sensor.dining_room_thermostat_operation_mode
      -  sensor.dining_room_thermostat_target
      -  sensor.dining_room_thermostat_temperature
    hours_to_show: 168
    # refresh: 0 

###############################################################
######  Include Files
###############################################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zone.yaml
sensor: !include sensor.yaml

