homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret castillo_lat
  longitude: !secret castillo_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret castillo_elev
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

frontend:

# Enables configuration UI
config:

http:
  api_password: !secret ha_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#view log of services
logger:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

#Alexa
alexa:

# Example configuration.yaml entry
device_tracker:
  - platform: icloud
    username: !secret ck_apple_id
    password: !secret ck_apple_pw
    account_name: !secret ck_apple_nm

device_tracker:
  - platform: icloud
    username: !secret ar_apple_id
    password: !secret ar_apple_pw
    account_name: !secret ar_apple_nm

device_tracker:
  platform: trackr
  username: !secret trackr_user
  password: !secret trackr_pass
    
#Rachio iframe panel_iframe
panel_iframe:
  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump

#Nest Integration
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
    
#Apple TV 
apple_tv:
  - host: !secret castillo_appletv_ip
    login_id: !secret castillo_appletv_login
    name: Apple TV 4K
 
#History Graph 
history_graph:
  gr2:
    name: Temperature
    entities:
      -  climate.dining_room
    hours_to_show: 168
    # refresh: 0 

group:
  evening_lights:
    - light.ge_14295_inwall_smart_toggle_dimmer_level
    - switch.ge_14282_plugin_twooutlet_smart_switch_switch
    
zwave:
  usb_path: /dev/ttyACM0
  
# IFTT Craig
ifttt:
  key: !secret iftt_key
  
#Zones for Map
zone:
  name: Home
  latitude: !secret castillo_lat
  longitude: !secret castillo_long
  radius: 200
  icon: mdi:home

zone 2:
  name: DWD
  latitude: !secret ck_work_lat
  longitude: !secret ck_work_long
  radius: 200
  icon: mdi:work

zone 3:
  name: Safeway
  latitude: !secret ar_work_lat
  longitude: !secret ar_work_long
  radius: 200
  icon: mdi:work
  
###############################################################
######  Include Files
###############################################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
