################################################################
## Packages / Weather
## Dependencies: DARKSKY - https://darksky.net/dev/
##               WUNDERGROUND - https://home-assistant.io/components/sensor.wunderground/
################################################################

homeassistant:
  customize:
    #DARKSKY
    sensor.dark_sky_apparent_temperature:
      friendly_name: 'Current Temperature'
      icon: mdi:thermometer
    sensor.dark_sky_daytime_high_apparent_temperature:
      friendly_name: 'Daily High'
      icon: mdi:thermometer
    sensor.dark_sky_overnight_low_temperature:
      friendly_name: 'Daily Low'
      icon: mdi:thermometer
    sensor.dark_sky_humidity:
      friendly_name: 'Current Humidity'
    sensor.dark_sky_temperature:
      friendly_name: 'Current Temperature'
#    sensor.dark_sky_daily_summary:
      friendly_name: 'Daily Summary'
    # UV
#    sensor.pws_uv:
#      friendly_name: 'UV Index'
#      icon: mdi:white-balance-sunny
#    sensor.uv_burn_time:
#      friendly_name: 'Burn Time'
#      icon: mdi:fire
    # WEATHER report
    script.weather_report:
      friendly_name: 'Weather Report'
      emulated_hue_hidden: false
      google_assistant: true
      google_assistant_name: 'Weather Report'

#WEATHER MAP
camera:
 - platform: generic
    still_image_url: !secret weather_radar
    name: Weather Radar

###### wunderground
#  - platform: wunderground
#    api_key: !secret wunderground_key
#    pws_id: !secret wunderground_station
#   monitored_conditions:
#     - UV
#     - precip_1d
